=== GabrielHoy/VSBloom/schemas/EffectConfig.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["effectDisplayName", "configurableProperties"],
    "properties": {
        "effectDisplayName": {
            "type": "string",
            "description": "The display name shown in the UI for this effect."
        },
        "disabled": {
            "type": "boolean",
            "default": false,
            "description": "Whether this effect is entirely disabled or not."
        },
        "cssVarPrefix": {
            "type": "string",
            "description": "The prefix for the CSS variables that correspond to the configurable properties in this effect's JSON file."
        },
        "configurableProperties": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "type", "default", "description"],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the configurable property which will be exposed to the user to configure in VSCode as well as exposed to TypeScript."
                    },
                    "type": {
                        "type": "string",
                        "description": "The data type of the configurable property.",
                        "enum": ["boolean", "string", "number"]
                    },
                    "default": {},
                    "description": {
                        "type": "string",
                        "description": "The description of the configurable property which will be shown in the UI to the user as an explanation for the property."
                    },
                    "markdownDescription": {
                        "type": "string",
                        "description": "Equivalent to the description property, but allowing for markdown formatting as well."
                    },
                    "enum": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description": "An array of possible values for the configurable property."
                    },
                    "step": {
                        "type": "number",
                        "description": "The step size for the configurable property in the VS Bloom Settings Editor. Note - this does not restrict users from inputting smaller steps."
                    },
                    "cssUnit": {
                        "type": "string",
                        "description": "A CSS unit string that will be appended to the CSS variable name for the configurable property when it is automatically pulled from the user's VS Code settings and forwarded into a CSS variable on the Electron Renderer's DOM :root element."
                    },
                    "isColor": {
                        "type": "boolean",
                        "description": "Whether the configurable property is a color or not. If true, the VS Bloom Settings Editor will automatically render an interactive color picker for the property."
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== GabrielHoy/VSBloom/src/Effects/Tabs/Tabs.json
{
    "effectDisplayName": "Tab Overhaul",
    "cssVarPrefix": "tabOverhaul",
    "disabled": false,
    "configurableProperties": [
        {
            "name": "enabled",
            "type": "boolean",
            "default": true,
            "description": "Enable or disable visual revamps applied to code editor tabs.",
            "markdownDescription": "Enable or disable visual revamps applied to code editor tabs."
        },
        {
            "name": "tabSeparatorStyle",
            "type": "string",
            "enum": [
                "dashed",
                "dotted",
                "solid"
            ],
            "cssUnit": "",
            "default": "dashed",
            "description": "The style of a separator border that appears between two open tabs.",
            "markdownDescription": "The style of a separator border that appears between two open tabs."
        },
        {
            "name": "glowSize",
            "type": "number",
            "cssUnit": "px",
            "default": 1,
            "description": "The size of a glow effect that appears on the text of a tab when it is active, in pixels.",
            "markdownDescription": "The size of a glow effect that appears on the text of a tab when it is active, in **pixels**."
        }
    ]
}

=== GabrielHoy/VSBloom/src/Effects/LineNumbers/LineNumbers.json
{
    "effectDisplayName": "Line Number Effects",
    "disabled": false,
    "cssVarPrefix": "lineNumbers",
    "configurableProperties": [
        {
            "name": "enabled",
            "type": "boolean",
            "default": true,
            "description": "Enable or disable line number indicator effects.",
            "markdownDescription": "Enable or disable line number indicator effects."
        },
        {
            "name": "activeLineAnimationDuration",
            "type": "number",
            "default": 0.35,
            "step": 0.05,
            "cssUnit": "s",
            "description": "The duration of the animation that occurs when the active line number changes, in seconds.",
            "markdownDescription": "The duration of the animation that occurs when the active line number changes, in **seconds**."
        },
        {
            "name": "activeLineOffset",
            "type": "number",
            "default": 3,
            "step": 0.5,
            "cssUnit": "px",
            "description": "The offset of the active line number to the right, in pixels.",
            "markdownDescription": "The offset of the active line number to the right, in **pixels**."
        },
        {
            "name": "activeLineGlowSize",
            "type": "number",
            "default": 2.5,
            "step": 0.25,
            "cssUnit": "px",
            "description": "The size of the glow effect around the active line number, in pixels.",
            "markdownDescription": "The size of the glow effect around the active line number, in **pixels**."
        },
        {
            "name": "activeLineSkewAngle",
            "type": "number",
            "default": -7.5,
            "step": 0.5,
            "cssUnit": "deg",
            "description": "The angle of the skew effect on the active line number's text, in degrees. Negative values allowed.",
            "markdownDescription": "The angle of the skew effect on the active line number's text, in **degrees**. *Negative values allowed.*"
        }
    ]
}
